### health check
GET http://localhost:8080 HTTP/1.1

### create user
POST http://localhost:8080/user/register HTTP/1.1
content-type: application/json

{
    "name": "Diego",
    "email": "user1@mail.com",
    "password": "password"
}


### add buddy to list
POST http://localhost:8080/user/friend/608f3a459968af13a59adc42 HTTP/1.1
Content-Type: application/json

{ 
    "email": "user@mail.com"
}

### register buddy once invited
POST http://localhost:8080/user/friend/register/60907ee3821daa2ab806a4b6 HTTP/1.1
Content-Type: application/json

{ 
    "name": "diego",
    "password": "password"
}

### me
GET http://localhost:8080/user/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGllZ28iLCJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIxLTA1LTAyVDIzOjQ4OjE1LjM3NFoiLCJsaXN0cyI6WyI2MDkwNzIzYWE3MGZjYzIxNzJmMGNhM2UiLCI2MDkxODA4Njc2ZjJhOTViZTJhYWUwM2YiXSwiX2lkIjoiNjA4ZjNhM2Y5OTY4YWYxM2E1OWFkYzQwIiwiaWF0IjoxNjIwMTc0NzUxfQ.EfgiBGLGhTKqBokhNGuAedqNF2YnRt5Lx1wmQRmkv5s

### logout
POST http://localhost:8080/user/logout HTTP/1.1

### create new list
POST http://localhost:8080/lists HTTP/1.1
Content-Type: application/json

{
    "name": "test list",
    "description": "yoo, im the description of a list"
}


### login
POST http://localhost:8080/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "user@mail.com",
    "password": "password"
}

### delete list
DELETE http://localhost:8080/lists/608f3a459968af13a59adc42 HTTP/1.1

### get list by id
GET http://localhost:8080/lists/608f3a459968af13a59adc42 HTTP/1.1

### create new list item
POST http://localhost:8080/lists/6081ea592e6f5366964b7efc HTTP/1.1
Content-Type: application/json

{
    "name": "test item",
    "description": "yoo, im the description of a list"
}

### delete list item
DELETE http://localhost:8080/lists/6081ea592e6f5366964b7efc/608761454e1df17f1a1a141b HTTP/1.1

### forgot password
POST http://localhost:8080/user/forgot-password HTTP/1.1
content-type: application/json

{
    "email": "dev.diego.romero@gmail.com"
}